running
setUp
"usuarioJuan"
usuarioJuan nombreUsuario: 'Juan de los Palotes'.
usuarioJuan password: '1234'.
usuarioJuan fechaCreacion: Date today.
usuarioJuan horaCreacion: Time now.
usuarioJuan seguidores: OrderedCollection new.
usuarioJuan siguiendo: OrderedCollection new.
usuarioJuan topicosFavoritos: OrderedCollection new.
"usuarioMaria"
usuarioMaria nombreUsuario: 'Maria Perez'.
usuarioMaria password: '4789'.
usuarioMaria fechaCreacion: Date today.
usuarioMaria horaCreacion: Time now.
usuarioMaria seguidores: OrderedCollection new.
usuarioMaria siguiendo: OrderedCollection new.
usuarioMaria topicosFavoritos: OrderedCollection new.
"usuarioMario"
usuarioMario nombreUsuario: 'Mario Rodriguez'.
usuarioMario password: '1457'.
usuarioMario fechaCreacion: Date today.
usuarioMario horaCreacion: Time now.
usuarioMario seguidores: OrderedCollection new.
usuarioMario siguiendo: OrderedCollection new.
usuarioMario topicosFavoritos: OrderedCollection new.
"usuarioAgustin"
usuarioAgustin nombreUsuario: 'Agustin Solari'.
usuarioAgustin password: '1779'.
usuarioAgustin fechaCreacion: Date today.
usuarioAgustin horaCreacion: Time now.
usuarioAgustin seguidores: OrderedCollection new.
usuarioAgustin siguiendo: OrderedCollection new.
usuarioAgustin topicosFavoritos: OrderedCollection new.
"usuarioPedro"
usuarioPedro nombreUsuario: 'Pedro Luque'.
usuarioPedro password: '4444'.
usuarioPedro fechaCreacion: Date today.
usuarioPedro horaCreacion: Time now.
usuarioPedro seguidores: OrderedCollection new.
usuarioPedro siguiendo: OrderedCollection new.
usuarioPedro topicosFavoritos: OrderedCollection new.